### PR TITLE
API Overhaul

### PR DESCRIPTION
**Pull request by founderio**
Currently:
- re-did the changes from before extraction + applied them on @Premke's fixes for new module name
- Default to json format & remove that pesky :format parameter from the routes
- More actual usage of the toJSON functions
- Adds the optional parameter 'nodetail' that disables detailed information on certain endpoints.
- Adds an endpoint to display a single project. (/api/:api_username/projects/:project_key)

### CODE REVIEW

**Comment by Premke** [comment]
Please check commit LogosLabs/thebuggenie@73a5a81d9a9963f311a3faa8d118453cc8b75e7c and apply changes accordingly. 

Unfortunately without tests @zegenie nor I could inform you, before thebuggenie/thebuggenie#448 was merged, that detailed output was important.

**Comment by founderio** [comment]
Ah, I was afraid of that.. Alright, will adjust the calls accordingly. Thanks!

**Comment by founderio** [comment]
Depends on LogosLabs/thebuggenie@73a5a81. ie PR thebuggenie/thebuggenie#449.
Especially because of the missing return in Milestone entity. The rest is more or less independent, as i now explicitly state if the detailed into should be returned.

**Comment by founderio** [comment]
Oh, and @Premke I'll be on IRC more frequently now (was not on freenode as of yet..) - just ping me if you find another derp of mine.

**Comment by Premke** [comment]
Duly noted. :)

**Comment by zegenie** [comment]
@Premke I can't merge PR thebuggenie/thebuggenie#449 as it is - can you make a separate PR for commit LogosLabs/thebuggenie@73a5a81 ?

**Comment by Premke** [comment]
@zegenie Sure here it is thebuggenie/thebuggenie#450, but can you elaborate on that PR why you can't merge it.

**Comment by zegenie** [comment]
@Premke I totally will - first of all, the PR is so huge I haven't had time to review it all yet and secondly there are a couple of changes in there (such as the cancel attachments functionality) that we should discuss further :)

**Comment by Premke** [comment]
@zegenie We are probably going offtopic on this PR. Take your time with review, I'll update PR accordingly to what we agree upon. And if possible add comments on commits we should discuss. 

About cancel attachments functionality, as you are aware it was possible to upload many files without ever linking them to issue / article which would take hard disk space for naught. Another approach would probably be some kind of cli command which would check all uploaded files and remove unlinked ones.

**Pull request merged**
